### ISSUE TITLE
Q-Slides

### ISSUE THREAD

**Issue by XDreamist** [PixellQ/3DAPE#2]
It is script-based slides maker just like Google slides but here we use our own scripts to make, animate, edit, change, etc.. Basically to do everything related slides. It will have much more flexibility allowing the users to Create, Edit, Share whatever they want by making use of the scripts and can be deployed anywhere platform regardless. 

   It will be available in pdf format for distributable purposes so that anybody from anywhere can access it. It is small project though

**Comment by arjunbchennithala** [comment]
I had another idea relating to presentations.
It's a synchronised slide presenter. Every one with credentials can access the live presentation. When one device joins the presentation it recieves the the copy of full slide. Only the audio of the presenter will be broadcasted to all viewers and when the presenter changes the pages That data will be broadcasted and the viewer can view the same page. Normally we need to broadcast video data only to share a slide. But when doing this, we can reduce the network bandwidth requirement and the presentation will be in full quality.

**Comment by XDreamist** [comment]
Ohhhh nalla idea, enik ingane thonniyilla. Ith kidukkum

**Comment by arjunbchennithala** [comment]
Enthaayalum ee ideas ellam recorded aanello. Nammakk pathukke pathukke ellaam analyse cheyth edukkaam.
